"""
Sentinel AI 2.0 - Autonomous Remediation & Reporting Tools
Generates standardized cybercrime complaint dossiers, Razorpay abuse takedown templates,
and customized consumer mitigation playbooks.
"""

import json
import datetime

def generate_cybercrime_complaint_payload(analysis_result: dict, input_text: str) -> dict:
    """
    Generates a pre-filled complaint structure formatted for India's National Cyber Crime Reporting Portal (cybercrime.gov.in).
    """
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S IST")
    category = "Financial Fraud / Phishing / Social Engineering"
    
    suspect_indicators = []
    if "osint" in analysis_result and "domains_analyzed" in analysis_result["osint"]:
        for d in analysis_result["osint"]["domains_analyzed"]:
            suspect_indicators.append(f"Malicious URL/Domain: {d.get('domain')}")
            
    if "fintech" in analysis_result and "vpas_analyzed" in analysis_result["fintech"]:
        for v in analysis_result["fintech"]["vpas_analyzed"]:
            suspect_indicators.append(f"Fraudulent UPI VPA: {v.get('vpa')}")

    complaint_text = f"""[CYBERCRIME COMPLAINT DRAFT - GENERATED BY SENTINEL AI]
Incident Timestamp: {timestamp}
Incident Category: {category}
Overall Risk Level: {analysis_result.get('overall_risk', 'High')}
Confidence Score: {analysis_result.get('confidence_score', 0)}%

1. INCIDENT BRIEF:
The complainant received an unsolicited communication containing deceptive social engineering, financial lures, or brand impersonation signals designed to induce unauthorized financial debits or credential theft.

2. SUSPECT ARTIFACTS & INDICATORS OF COMPROMISE (IoCs):
{chr(10).join(f"- {ind}" for ind in suspect_indicators) if suspect_indicators else "- Extracted from communication payload below."}

3. RAW EVIDENCE TEXT:
\"\"\"{input_text}\"\"\"

4. FORENSIC REASONING SUMMARY:
{chr(10).join(f"- {r.get('title')}: {r.get('text')}" for r in analysis_result.get('analysis', []))}

5. RELIEF / ACTION REQUESTED:
- Issue immediate block on the suspect domain / host IP.
- Alert associated Payment Service Providers (PSPs) regarding fraudulent VPA / merchant activity.
- Preserve server logs under Section 91 of CrPC for further cyber forensics.
"""
    return {
        "portal": "National Cyber Crime Reporting Portal (https://cybercrime.gov.in)",
        "helpline": "1930",
        "timestamp": timestamp,
        "complaint_draft": complaint_text
    }


def generate_razorpay_abuse_takedown_notice(analysis_result: dict, spoofed_domain: str = "") -> dict:
    """
    Generates a formal abuse & brand phishing notification addressed to abuse@razorpay.com and domain registrars.
    """
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S IST")
    
    takedown_notice = f"""To: abuse@razorpay.com, security@razorpay.com
Subject: [URGENT] Phishing & Unauthorized Brand Impersonation Alert - {spoofed_domain or 'Spoofed Gateway'}
Date: {timestamp}

Dear Razorpay Security & Trust/Safety Team,

Sentinel AI Autonomous Defense Agent has detected an unauthorized infrastructure asset mimicking Razorpay's trusted checkout and merchant infrastructure.

Threat Details:
- Target Brand: Razorpay Payments / Gateway
- Offending Domain / Asset: {spoofed_domain or 'Detected in payload'}
- Risk Classification: CRITICAL PHISHING / FINANCIAL FRAUD

Automated Evidence & Findings:
- Brand lookalike / spoofing detection triggered.
- Impersonation of official payment gateway interfaces (`pages.razorpay.com` / `rzp.io`).
- Intended Impact: Theft of user payment credentials / fraudulent UPI debits.

Requested Action:
1. Initiate trademark / brand infringement takedown against host / registrar.
2. Blacklist associated beneficiary merchant ID / VPA across Razorpay Shield & Thirdwatch networks.
3. Submit domain to Google Safe Browsing and Microsoft SmartScreen feeds.

Generated autonomously by Sentinel AI 2.0 Security Operations Engine.
"""
    return {
        "recipient": "abuse@razorpay.com",
        "subject": f"[URGENT] Brand Phishing Report - {spoofed_domain}",
        "body": takedown_notice
    }


def generate_safety_playbook(risk_level: str, vectors: list[str]) -> list[dict]:
    """
    Generates an immediate, actionable defense checklist for the end-user.
    """
    steps = []
    
    if risk_level in ["High", "Medium–High"]:
        steps.append({
            "step": 1,
            "title": "🚨 Do NOT Tap Links or Enter Credentials",
            "action": "Avoid clicking links or entering passwords, OTPs, or debit/credit card numbers on the provided page."
        })
        steps.append({
            "step": 2,
            "title": "🛑 Never Enter UPI PIN to Receive Money",
            "action": "Remember: UPI PIN is strictly for DEBITING funds from your account. Receiving refunds or cashbacks never requires a PIN."
        })
        steps.append({
            "step": 3,
            "title": "📞 Dial 1930 in Case of Financial Loss",
            "action": "If any money was transferred, immediately call the National Cyber Helpline (1930) or report at cybercrime.gov.in within the golden hour."
        })
        steps.append({
            "step": 4,
            "title": "🛡️ Block & Report the Sender",
            "action": "Mark message as Spam/Phishing in WhatsApp/SMS app and block the sender number/VPA."
        })
    else:
        steps.append({
            "step": 1,
            "title": "✅ Standard Verification",
            "action": "While no critical scam signals were detected, always ensure you are on the verified official domain (e.g., razorpay.com, your official bank app)."
        })
        steps.append({
            "step": 2,
            "title": "🔒 Keep 2FA Enabled",
            "action": "Maintain Two-Factor Authentication on all banking and email accounts."
        })

    return steps

